name: Publish Packages to Nuget
on:
  release:
    types: [published]

jobs:
  publish:
    name: Pack and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package WillSoss.Data
        run: dotnet pack WillSoss.Data/WillSoss.Data.csproj -c Release -o feeds/nuget

      - name: Package WillSoss.Data.Sql
        run: dotnet pack WillSoss.Data.Sql/WillSoss.Data.Sql.csproj -c Release -o feeds/nuget

      - name: Push to Nuget
        run: find feeds/nuget -name '*.nupkg' | xargs -i dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}